<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>detail_jobdesc</name>
   <tag></tag>
   <elementGuidId>65355453-93ae-4bda-af9a-86ee1affe3f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chakra-modal--body-:r6:']/div/div[3]/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.chakra-stack.css-yx1mjj</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0bcc6235-2cf3-4eec-9c85-eb42e50d9444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-stack css-yx1mjj</value>
      <webElementGuid>659ac568-c8db-4aa8-8b95-7ed9b8c9ff12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>90ba8342-ebfa-4de8-be16-6cf697a29d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Job DescriptionResponsibilitiesCurrently, we are looking for a Senior Game Designer to specifically work on our Origin game - try the latest version here (https://app.axieinfinity.com/games/origins/). The possibilities and creativity that can go into this ambitious project are truly infinite.Being a Senior Game Designer at Sky Mavis, you are expected to:Define and drive alignment on the vision and direction for the game designDesign and development of game narratives, mechanics, progression systems, rewards, monetization models, and any other game design-related componentsCollaborate closely with other departments (art, UX, engineering, product, QA, etc.) to ship new game features and ensure they meet a high standard of qualityTune and balance the gameplay and economy to maximize sustainable fun and rewards for playersIntroduce best practices around game design to the team and mentor other game designersIncorporate quantitative and qualitative data from players to inform game designsRequirementExperience playing, designing, balancing, and managing economies for card games (e.g. Hearthstone, Magic the Gathering, Legends of Runeterra, Yugioh, Pokemon TCG) or other relevant game genresExcited about building innovative and novel game mechanics that leverage the power of immutable digital assets on the blockchainHighly proficient in System Design, Game balance, In-game Economy or Monetization5+ years experience designing, balancing, and tuning complex games with a significant number of daily active users.Experience using data to inform decisions, model game systems, and predict outcomesA strong sense of what makes a gameplay experience compelling and fun, as well as the ability to articulate well why a game design decision is good or badStrong written and oral communication skills to ensure alignment around game designs across cross-functional teamsTeam player and can work closely with the rest of our team to ship and test featuresExperience or interest in token omics and blockchain game designGood project management and time management skills, with a proven ability to focus on top priorities, solve problems, juggle multiple tasks, and meet deadlinesExcellent communication, interpersonal, and organizational skillsGenuine interest and passion for gamesCapable of working with little to no direct supervision. Self-motivated and actively take initiative</value>
      <webElementGuid>70df6483-1728-4376-9c58-1349b79b9b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal--body-:r6:&quot;)/div[@class=&quot;chakra-stack career-job-detail css-142jvh9&quot;]/div[@class=&quot;chakra-stack css-p2hcye&quot;]/div[@class=&quot;chakra-stack css-yx1mjj&quot;]</value>
      <webElementGuid>bfc91f6a-8aa4-40b4-b385-7b848e17915b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-:r6:']/div/div[3]/div[3]</value>
      <webElementGuid>e35f6b7f-7ff0-4fbb-b8e8-8ba1de3b564f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blockchain'])[2]/following::div[1]</value>
      <webElementGuid>60bc3ca5-c292-4fa6-b9af-962b82857c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In-game Monetization'])[2]/following::div[1]</value>
      <webElementGuid>b5579ae5-7e95-4513-aaa8-30d0044affda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div[3]</value>
      <webElementGuid>b9dbea43-ef22-4845-b1d7-5fa068dd9405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Job DescriptionResponsibilitiesCurrently, we are looking for a Senior Game Designer to specifically work on our Origin game - try the latest version here (https://app.axieinfinity.com/games/origins/). The possibilities and creativity that can go into this ambitious project are truly infinite.Being a Senior Game Designer at Sky Mavis, you are expected to:Define and drive alignment on the vision and direction for the game designDesign and development of game narratives, mechanics, progression systems, rewards, monetization models, and any other game design-related componentsCollaborate closely with other departments (art, UX, engineering, product, QA, etc.) to ship new game features and ensure they meet a high standard of qualityTune and balance the gameplay and economy to maximize sustainable fun and rewards for playersIntroduce best practices around game design to the team and mentor other game designersIncorporate quantitative and qualitative data from players to inform game designsRequirementExperience playing, designing, balancing, and managing economies for card games (e.g. Hearthstone, Magic the Gathering, Legends of Runeterra, Yugioh, Pokemon TCG) or other relevant game genresExcited about building innovative and novel game mechanics that leverage the power of immutable digital assets on the blockchainHighly proficient in System Design, Game balance, In-game Economy or Monetization5+ years experience designing, balancing, and tuning complex games with a significant number of daily active users.Experience using data to inform decisions, model game systems, and predict outcomesA strong sense of what makes a gameplay experience compelling and fun, as well as the ability to articulate well why a game design decision is good or badStrong written and oral communication skills to ensure alignment around game designs across cross-functional teamsTeam player and can work closely with the rest of our team to ship and test featuresExperience or interest in token omics and blockchain game designGood project management and time management skills, with a proven ability to focus on top priorities, solve problems, juggle multiple tasks, and meet deadlinesExcellent communication, interpersonal, and organizational skillsGenuine interest and passion for gamesCapable of working with little to no direct supervision. Self-motivated and actively take initiative' or . = 'Job DescriptionResponsibilitiesCurrently, we are looking for a Senior Game Designer to specifically work on our Origin game - try the latest version here (https://app.axieinfinity.com/games/origins/). The possibilities and creativity that can go into this ambitious project are truly infinite.Being a Senior Game Designer at Sky Mavis, you are expected to:Define and drive alignment on the vision and direction for the game designDesign and development of game narratives, mechanics, progression systems, rewards, monetization models, and any other game design-related componentsCollaborate closely with other departments (art, UX, engineering, product, QA, etc.) to ship new game features and ensure they meet a high standard of qualityTune and balance the gameplay and economy to maximize sustainable fun and rewards for playersIntroduce best practices around game design to the team and mentor other game designersIncorporate quantitative and qualitative data from players to inform game designsRequirementExperience playing, designing, balancing, and managing economies for card games (e.g. Hearthstone, Magic the Gathering, Legends of Runeterra, Yugioh, Pokemon TCG) or other relevant game genresExcited about building innovative and novel game mechanics that leverage the power of immutable digital assets on the blockchainHighly proficient in System Design, Game balance, In-game Economy or Monetization5+ years experience designing, balancing, and tuning complex games with a significant number of daily active users.Experience using data to inform decisions, model game systems, and predict outcomesA strong sense of what makes a gameplay experience compelling and fun, as well as the ability to articulate well why a game design decision is good or badStrong written and oral communication skills to ensure alignment around game designs across cross-functional teamsTeam player and can work closely with the rest of our team to ship and test featuresExperience or interest in token omics and blockchain game designGood project management and time management skills, with a proven ability to focus on top priorities, solve problems, juggle multiple tasks, and meet deadlinesExcellent communication, interpersonal, and organizational skillsGenuine interest and passion for gamesCapable of working with little to no direct supervision. Self-motivated and actively take initiative')]</value>
      <webElementGuid>ea7a7dba-85f4-44b4-b5c0-0ad9f8fe4743</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
