<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>list_Job</name>
   <tag></tag>
   <elementGuidId>d63d3c3a-11f0-44a5-a2c2-310022ce0543</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.chakra-stack.css-rozekk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;content-center&quot;]/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>695982ba-e15c-4648-86e9-ae53ea68a894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-stack css-rozekk</value>
      <webElementGuid>e5de40a8-0900-4aa2-96e9-a1bcd9e38720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Senior Game Designer - OriginsSky Mavis - Vietnam - Ho Chi Minh CityOn-siteNegotiable/mBlockchainGame BalanceIn-game EconomyIn-game MonetizationSystem Design</value>
      <webElementGuid>c2e7d6e7-eaa9-43c7-b335-2529fb6db4a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-center&quot;)/div[@class=&quot;css-16gze1t&quot;]/div[@class=&quot;infinite-scroll-component__outerdiv&quot;]/div[@class=&quot;infinite-scroll-component&quot;]/div[@class=&quot;chakra-stack css-qzvunm&quot;]/div[@class=&quot;chakra-stack css-rozekk&quot;]</value>
      <webElementGuid>1de958b9-3fb9-4126-84f3-feb67e6ccdbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-center']/div[2]/div/div/div/div</value>
      <webElementGuid>329e5a46-24e8-4fac-839c-1e4806c7cf28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DevOps'])[1]/following::div[6]</value>
      <webElementGuid>0e39977f-abaa-4c56-8190-807650a08e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Java'])[1]/following::div[6]</value>
      <webElementGuid>f84def02-b7e6-450f-8a37-0d420f6ff340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div[2]/div/div/div/div</value>
      <webElementGuid>16b93dea-6b0f-4ac5-9f10-ae790082e320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Senior Game Designer - OriginsSky Mavis - Vietnam - Ho Chi Minh CityOn-siteNegotiable/mBlockchainGame BalanceIn-game EconomyIn-game MonetizationSystem Design' or . = 'Senior Game Designer - OriginsSky Mavis - Vietnam - Ho Chi Minh CityOn-siteNegotiable/mBlockchainGame BalanceIn-game EconomyIn-game MonetizationSystem Design')]</value>
      <webElementGuid>d756829c-c95f-4b44-b552-61dc8e5b96ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
