<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Fullstack</name>
   <tag></tag>
   <elementGuidId>cd978775-ae7a-4cd9-8ac7-c5d25518ac56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-center']/div/div[2]/div/div/div[2]/span[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3946799f-253f-42cb-bb37-c1d15140082c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-15m7z1d</value>
      <webElementGuid>380441e8-180a-4afa-ad2d-ddf61067fcaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fullstack</value>
      <webElementGuid>71797727-c7be-4c3a-b3dc-d1d17a4fac92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-center&quot;)/div[@class=&quot;chakra-stack css-1xtdw5h&quot;]/div[@class=&quot;css-r0xern&quot;]/div[@class=&quot;css-syibrv&quot;]/div[@class=&quot;css-ohyvb6&quot;]/div[@class=&quot;css-1wp7ay0&quot;]/span[@class=&quot;css-15m7z1d&quot;]</value>
      <webElementGuid>e89cbdc2-909a-44fc-95a3-fa33d46f3ce3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-center']/div/div[2]/div/div/div[2]/span[3]</value>
      <webElementGuid>73589a15-e5e1-42fc-b733-dccf04b1edaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frontend'])[1]/following::span[1]</value>
      <webElementGuid>39101f30-e34c-49d8-9b0e-ba01a7f74707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Backend'])[1]/following::span[3]</value>
      <webElementGuid>2ae5b2d5-5807-45a7-92f7-9a18aa353e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Java'])[1]/preceding::span[2]</value>
      <webElementGuid>99b25ecc-0988-4388-9e7a-c379d35686ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/span[3]</value>
      <webElementGuid>b7f08eed-c725-4b11-ba94-f14e25060f4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Fullstack' or . = 'Fullstack')]</value>
      <webElementGuid>23745924-7840-48d6-8730-cbc753431f52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
