<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Java</name>
   <tag></tag>
   <elementGuidId>479c9931-c9cf-4284-9e3d-e522d376086a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-center']/div/div[2]/div/div/div[2]/span[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>53c90d36-cc3e-4a7a-bf33-238cee2df803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-15m7z1d</value>
      <webElementGuid>8890fb32-72a9-4d6d-9719-95282061ea8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Java</value>
      <webElementGuid>532682cb-64b0-45dc-8dbb-9dc3fe4bf3b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-center&quot;)/div[@class=&quot;chakra-stack css-1xtdw5h&quot;]/div[@class=&quot;css-r0xern&quot;]/div[@class=&quot;css-syibrv&quot;]/div[@class=&quot;css-ohyvb6&quot;]/div[@class=&quot;css-1wp7ay0&quot;]/span[@class=&quot;css-15m7z1d&quot;]</value>
      <webElementGuid>a822c432-ee1f-4ff3-a37d-c0a0c9794015</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-center']/div/div[2]/div/div/div[2]/span[4]</value>
      <webElementGuid>a27320c3-50a3-4acb-8d5d-e73b33a8e459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fullstack'])[1]/following::span[1]</value>
      <webElementGuid>d5b370dd-8417-45af-927e-d9fdcda1919d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frontend'])[1]/following::span[3]</value>
      <webElementGuid>5b41aa3e-c921-42ab-818b-0acde2ce9ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DevOps'])[1]/preceding::span[2]</value>
      <webElementGuid>ac6b2467-3f2b-4891-bfc7-e9501fd3855b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/span[4]</value>
      <webElementGuid>80748ba5-3f94-4d1f-9920-2030f2bf5824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Java' or . = 'Java')]</value>
      <webElementGuid>ea667ea6-67a5-4197-80f2-32d179969cbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
