<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_DevOps</name>
   <tag></tag>
   <elementGuidId>c47ebfcc-9c59-43c9-8f11-97cd9c96c1ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-center']/div/div[2]/div/div/div[2]/span[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b86b2035-a3cd-48b7-a893-be4709fef456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-15m7z1d</value>
      <webElementGuid>6254b47e-fe30-4538-affb-478fb83b5e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DevOps</value>
      <webElementGuid>29f27f7b-2fce-4e61-8a6a-0d10c390db77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-center&quot;)/div[@class=&quot;chakra-stack css-1xtdw5h&quot;]/div[@class=&quot;css-r0xern&quot;]/div[@class=&quot;css-syibrv&quot;]/div[@class=&quot;css-ohyvb6&quot;]/div[@class=&quot;css-1wp7ay0&quot;]/span[@class=&quot;css-15m7z1d&quot;]</value>
      <webElementGuid>3389bdc0-a266-451d-acae-84542660591f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-center']/div/div[2]/div/div/div[2]/span[5]</value>
      <webElementGuid>4e94b37e-f761-49aa-9070-9a128d24cf51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Java'])[1]/following::span[1]</value>
      <webElementGuid>5f8bfedb-fa9a-4fc4-a4cd-84e134d690d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fullstack'])[1]/following::span[3]</value>
      <webElementGuid>f254b343-8be9-4658-93b7-f0bc73d7e935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blockchain'])[1]/preceding::span[3]</value>
      <webElementGuid>472c5b7c-6f2b-4ce8-a60d-82d553653dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]</value>
      <webElementGuid>8ef29b67-6bbb-4d71-b3f5-fb74f72b4263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'DevOps' or . = 'DevOps')]</value>
      <webElementGuid>b7da4163-e3da-4d86-b5fd-9902cb4f360b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
