<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Backend</name>
   <tag></tag>
   <elementGuidId>d0d91fbb-49c2-463c-b7b7-e68e4659d1b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-center']/div/div[2]/div/div/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.css-15m7z1d</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>485c3202-24d1-43e3-9c2f-69350f2cfb45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-15m7z1d</value>
      <webElementGuid>b6620c51-b831-4523-9cea-0f4a37cb1daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Backend</value>
      <webElementGuid>1f7735e0-2a8f-4471-9c5d-ba612084c947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-center&quot;)/div[@class=&quot;chakra-stack css-1xtdw5h&quot;]/div[@class=&quot;css-r0xern&quot;]/div[@class=&quot;css-syibrv&quot;]/div[@class=&quot;css-ohyvb6&quot;]/div[@class=&quot;css-1wp7ay0&quot;]/span[@class=&quot;css-15m7z1d&quot;]</value>
      <webElementGuid>2fa32bb5-9fba-41a1-b043-9e33694c8afe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-center']/div/div[2]/div/div/div[2]/span</value>
      <webElementGuid>e50b585d-755b-4d44-8f55-51cbd31ebc95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search ...'])[1]/following::span[1]</value>
      <webElementGuid>90310638-5407-496a-bc05-4aac7792d633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Timezone ...'])[1]/following::span[3]</value>
      <webElementGuid>b74780eb-4a0f-44db-b338-9186d1748616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frontend'])[1]/preceding::span[2]</value>
      <webElementGuid>8bfd40ee-8163-49dd-850b-78a3b7af5827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/span</value>
      <webElementGuid>64159ad8-385f-4b51-8c48-627cbab425d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Backend' or . = 'Backend')]</value>
      <webElementGuid>b7a835ce-5165-48ab-b312-3d54a9bc8465</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
