<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Frontend</name>
   <tag></tag>
   <elementGuidId>7e0e9ffc-ca10-4b89-898e-96a517912a00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-center']/div/div[2]/div/div/div[2]/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4f0b2c51-4e3c-4a4e-8186-80c89ee0d57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-15m7z1d</value>
      <webElementGuid>88175360-6e4b-4e96-adfd-8e8ff9352f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Frontend</value>
      <webElementGuid>f14d3ce1-c2ed-431e-a35b-216d4525aa58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-center&quot;)/div[@class=&quot;chakra-stack css-1xtdw5h&quot;]/div[@class=&quot;css-r0xern&quot;]/div[@class=&quot;css-syibrv&quot;]/div[@class=&quot;css-ohyvb6&quot;]/div[@class=&quot;css-1wp7ay0&quot;]/span[@class=&quot;css-15m7z1d&quot;]</value>
      <webElementGuid>020fb546-f0ad-40cf-abd4-2ea9f6a8de82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-center']/div/div[2]/div/div/div[2]/span[2]</value>
      <webElementGuid>1012260d-daa0-45d7-a26d-99006cc6c9c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Backend'])[1]/following::span[1]</value>
      <webElementGuid>51297caf-b115-43bf-8c9a-145744426348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search ...'])[1]/following::span[3]</value>
      <webElementGuid>b28c1020-12be-4a60-b876-0c27f8ee2c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fullstack'])[1]/preceding::span[2]</value>
      <webElementGuid>7bf38675-35ec-4bed-bae4-c8d12c14716a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/span[2]</value>
      <webElementGuid>925ce573-e836-4aa7-af31-d4869b0dc711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Frontend' or . = 'Frontend')]</value>
      <webElementGuid>faf659c4-f3d2-448b-b4ed-9bb72385c351</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
