<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title_job</name>
   <tag></tag>
   <elementGuidId>d40cd169-265f-42c6-b0df-78186618aa92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chakra-modal--body-:r6:']/div/div[2]/div[2]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.chakra-text.css-1e11nn2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>473a7577-c0e8-418c-8d43-3d6a9e7feef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-text css-1e11nn2</value>
      <webElementGuid>fb86fc40-d25d-43ee-ad92-c744b521fdca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Senior Game Designer - Origins</value>
      <webElementGuid>c937cf60-47b0-4fff-baab-579d10f3f158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal--body-:r6:&quot;)/div[@class=&quot;chakra-stack career-job-detail css-142jvh9&quot;]/div[@class=&quot;chakra-stack css-19akpcb&quot;]/div[@class=&quot;css-5cizd5&quot;]/p[@class=&quot;chakra-text css-1e11nn2&quot;]</value>
      <webElementGuid>487cf2b6-cf61-4035-97b2-af09872013a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-:r6:']/div/div[2]/div[2]/p</value>
      <webElementGuid>6c349f9e-a4c3-4327-8a12-0a5c3aa41b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full-time'])[2]/following::p[2]</value>
      <webElementGuid>be59f716-728f-44d8-b4d6-aba90eefb8cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On-site'])[4]/following::p[2]</value>
      <webElementGuid>3666eefb-6261-4bf4-88cb-8d12261abf6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A competitive salary package that fits your skills, experiences, and contributions.'])[1]/preceding::p[8]</value>
      <webElementGuid>f8bd7965-d51c-4efe-ae3e-94975cb39bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Give you freedom &amp; ownership of your work.'])[1]/preceding::p[8]</value>
      <webElementGuid>4597fa5b-9c68-4c68-ba16-d9e949f759cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div[2]/p</value>
      <webElementGuid>df20dda9-1104-4b69-97d1-afc872ca3fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Senior Game Designer - Origins' or . = 'Senior Game Designer - Origins')]</value>
      <webElementGuid>5234bf7b-922d-42dd-9916-64910f1c7893</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
